# CI for Product Catalog ervice

name: CI for Product Catalog Service

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: setup Go 1.22
              uses: actions/setup-go@v2
              with:
                  go-version: 1.22

            - name: Build
              run: cd src/product-catalog && go mod download && go build -o product-catalog-service main.go

            - name: unit tests
              run: cd src/product-catalog && go test ./...

    code-quality:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Run golangci-lint
              run: |
                go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.57.2
                export PATH=$PATH:$(go env GOPATH)/bin
                cd src/product-catalog
                golangci-lint run ./...

    docker:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Install Docker
              uses: docker/setup-buildx-action@v1

            - name: Login to Docker
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Docker Push
              uses: docker/build-push-action@v6
              with:
                  context: src/product-catalog
                  file: Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}
    
    updateK8s:
        runs-on: ubuntu-latest
        needs: docker
        steps:
            - name: checkout code
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GH_TOKEN }}`

            - name: Update tag in kubernetes deployment menifest
              run: |
                    sed -i 's/image: .*/image: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}/' kubernetes/productcatalog/deploy.yaml

            - name: Commit and push changers
              run: |
                git config --global user.name "${{secrets.GH_USER_NAME}}"
                git config --global user.email "${{secrets.GH_USER_EMAIL}}"
                git add kubernetes/productcatalog/deploy.yaml
                git commit -m "[CI]: Update image tag to ${{ github.run_id }}" || echo "No changes to commit"
                git push

